// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI migrate/db push targets local SQLite.
    // Production Turso schema is applied via: npm run db:push:turso
    url: process.env["DATABASE_URL"],
  },
});
